services:
# Keycloak DB
  postgres:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - /home/hoangnx/Documents/docker_compose/data/postgres:/var/lib/postgresql/data
    restart: always

# Keycloak server
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123

      KC_HOSTNAME: localhost
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      TZ: Asia/Ho_Chi_Minh
    command:
      - start-dev
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    restart: always
    volumes:
      - /home/hoangnx/Documents/docker_compose/data/keycloak:/opt/keycloak/data

# Web DB
  postgres-be-db:
    image: postgis/postgis:15-3.4
    container_name: postgres-be-db
    environment:
      POSTGRES_DB: bka
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - /home/hoangnx/Documents/docker_compose/data/postgres-web-db:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'

# Kafka service
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - /home/hoangnx/Documents/docker_compose/data/kafka:/bitnami/kafka


volumes:
  keycloak_data:
  postgres_data:


# 3 broker kafka
#networks:
#  kafka-net:
#    driver: bridge
#  kafka-1:
#    image: bitnami/kafka:3.7.0
#    container_name: kafka-1
#    hostname: kafka-1
#    networks:
#      - kafka-net
#    ports:
#      - "9094:9094"
#    environment:
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_KRAFT_CLUSTER_ID=Xa8N4zHkT3C9QXf2jH7ZJw
#
#  kafka-2:
#    image: bitnami/kafka:3.7.0
#    container_name: kafka-2
#    hostname: kafka-2
#    networks:
#      - kafka-net
#    ports:
#      - "9095:9095"
#    environment:
#      - KAFKA_CFG_NODE_ID=2
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:9095
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_KRAFT_CLUSTER_ID=Xa8N4zHkT3C9QXf2jH7ZJw
#
#  kafka-3:
#    image: bitnami/kafka:3.7.0
#    container_name: kafka-3
#    hostname: kafka-3
#    networks:
#      - kafka-net
#    ports:
#      - "9096:9096"
#    environment:
#      - KAFKA_CFG_NODE_ID=3
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9092,EXTERNAL://localhost:9096
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_KRAFT_CLUSTER_ID=Xa8N4zHkT3C9QXf2jH7ZJw

