spring:
  application:
    name: authentication-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bka
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}


jwt:
  auth:
    converter:
      resource-id: ${keycloak.adminClientId}
      principal-attribute: preferred_username

keycloak:
  realm: bka
  domain: localhost:8090
  adminClientId: bka_app
  adminClientSecret: ${KEYCLOAK_SECRET_KEY:JBIlGc9mx1WeLTGqgbhDTYUfftJBkrlK}
  admin:
    username: admin
    password: admin123
    realm: master
    clientId: admin-cli
  urls: http://${keycloak.domain}

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
    file: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSZ}","level":"%p","service":"${spring.application.name:-unknown}","env":"${spring.profiles.active:-local}","thread":"%t","class":"%C{1}.%M:%L","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","requestId":"%X{requestId:-}","message":"%replace(%msg){"\n"," "}"}'
  file:
    name: logs/authentication_service.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


