spring:
  application:
    name: post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.41:5432/post
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}


jwt:
  auth:
    converter:
      resource-id: ${keycloak.clientId}
      principal-attribute: preferred_username

keycloak:
  realm: bka
  domain: 192.168.3.41:8090
  clientId: bka_app
  clientSecret: JBIlGc9mx1WeLTGqgbhDTYUfftJBkrlK
  admin:
    username: admin
    password: admin123
    realm: master
    clientId: admin-cli
  urls: http://${keycloak.domain}


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
    file: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSZ}","level":"%p","service":"${spring.application.name:-unknown}","env":"${spring.profiles.active:-local}","thread":"%t","class":"%C{1}.%M:%L","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","requestId":"%X{requestId:-}","message":"%replace(%msg){"\n"," "}"}'
  file:
    name: logs/post_service.log
server:
  port: 8081

minio:
  url: http://192.168.3.41:9000
  username: bkaadmin
  password: bkaadmin
  attachments-bucket: attachment